spring:
  datasource:
    url: 
    username:
    password:
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show_sql: true
    database: oracle

logging:
  level:
    org.hibernate.SQL: debug

